export type PokemonSearchEntry = {
  value: string;
  label: string;
  show: boolean;
};

export const POKEMON_SEARCH_ENTRIES: PokemonSearchEntry[] = [
  { value: "bulbasaur", label: "Bulbasaur", show: true },
  { value: "ivysaur", label: "Ivysaur", show: true },
  { value: "venusaur", label: "Venusaur", show: true },
  { value: "charmander", label: "Charmander", show: true },
  { value: "charmeleon", label: "Charmeleon", show: true },
  { value: "charizard", label: "Charizard", show: true },
  { value: "squirtle", label: "Squirtle", show: true },
  { value: "wartortle", label: "Wartortle", show: true },
  { value: "blastoise", label: "Blastoise", show: true },
  { value: "caterpie", label: "Caterpie", show: true },
  { value: "metapod", label: "Metapod", show: true },
  { value: "butterfree", label: "Butterfree", show: true },
  { value: "weedle", label: "Weedle", show: true },
  { value: "kakuna", label: "Kakuna", show: true },
  { value: "beedrill", label: "Beedrill", show: true },
  { value: "pidgey", label: "Pidgey", show: true },
  { value: "pidgeotto", label: "Pidgeotto", show: true },
  { value: "pidgeot", label: "Pidgeot", show: true },
  { value: "rattata", label: "Rattata", show: true },
  { value: "raticate", label: "Raticate", show: true },
  { value: "spearow", label: "Spearow", show: true },
  { value: "fearow", label: "Fearow", show: true },
  { value: "ekans", label: "Ekans", show: true },
  { value: "arbok", label: "Arbok", show: true },
  { value: "pikachu", label: "Pikachu", show: true },
  { value: "raichu", label: "Raichu", show: true },
  { value: "sandshrew", label: "Sandshrew", show: true },
  { value: "sandslash", label: "Sandslash", show: true },
  { value: "nidoran-f", label: "Nidoran♀", show: true },
  { value: "nidorina", label: "Nidorina", show: true },
  { value: "nidoqueen", label: "Nidoqueen", show: true },
  { value: "nidoran-m", label: "Nidoran♂", show: true },
  { value: "nidorino", label: "Nidorino", show: true },
  { value: "nidoking", label: "Nidoking", show: true },
  { value: "clefairy", label: "Clefairy", show: true },
  { value: "clefable", label: "Clefable", show: true },
  { value: "vulpix", label: "Vulpix", show: true },
  { value: "ninetales", label: "Ninetales", show: true },
  { value: "jigglypuff", label: "Jigglypuff", show: true },
  { value: "wigglytuff", label: "Wigglytuff", show: true },
  { value: "zubat", label: "Zubat", show: true },
  { value: "golbat", label: "Golbat", show: true },
  { value: "oddish", label: "Oddish", show: true },
  { value: "gloom", label: "Gloom", show: true },
  { value: "vileplume", label: "Vileplume", show: true },
  { value: "paras", label: "Paras", show: true },
  { value: "parasect", label: "Parasect", show: true },
  { value: "venonat", label: "Venonat", show: true },
  { value: "venomoth", label: "Venomoth", show: true },
  { value: "diglett", label: "Diglett", show: true },
  { value: "dugtrio", label: "Dugtrio", show: true },
  { value: "meowth", label: "Meowth", show: true },
  { value: "persian", label: "Persian", show: true },
  { value: "psyduck", label: "Psyduck", show: true },
  { value: "golduck", label: "Golduck", show: true },
  { value: "mankey", label: "Mankey", show: true },
  { value: "primeape", label: "Primeape", show: true },
  { value: "growlithe", label: "Growlithe", show: true },
  { value: "arcanine", label: "Arcanine", show: true },
  { value: "poliwag", label: "Poliwag", show: true },
  { value: "poliwhirl", label: "Poliwhirl", show: true },
  { value: "poliwrath", label: "Poliwrath", show: true },
  { value: "abra", label: "Abra", show: true },
  { value: "kadabra", label: "Kadabra", show: true },
  { value: "alakazam", label: "Alakazam", show: true },
  { value: "machop", label: "Machop", show: true },
  { value: "machoke", label: "Machoke", show: true },
  { value: "machamp", label: "Machamp", show: true },
  { value: "bellsprout", label: "Bellsprout", show: true },
  { value: "weepinbell", label: "Weepinbell", show: true },
  { value: "victreebel", label: "Victreebel", show: true },
  { value: "tentacool", label: "Tentacool", show: true },
  { value: "tentacruel", label: "Tentacruel", show: true },
  { value: "geodude", label: "Geodude", show: true },
  { value: "graveler", label: "Graveler", show: true },
  { value: "golem", label: "Golem", show: true },
  { value: "ponyta", label: "Ponyta", show: true },
  { value: "rapidash", label: "Rapidash", show: true },
  { value: "slowpoke", label: "Slowpoke", show: true },
  { value: "slowbro", label: "Slowbro", show: true },
  { value: "magnemite", label: "Magnemite", show: true },
  { value: "magneton", label: "Magneton", show: true },
  { value: "farfetchd", label: "Farfetch’d", show: true },
  { value: "doduo", label: "Doduo", show: true },
  { value: "dodrio", label: "Dodrio", show: true },
  { value: "seel", label: "Seel", show: true },
  { value: "dewgong", label: "Dewgong", show: true },
  { value: "grimer", label: "Grimer", show: true },
  { value: "muk", label: "Muk", show: true },
  { value: "shellder", label: "Shellder", show: true },
  { value: "cloyster", label: "Cloyster", show: true },
  { value: "gastly", label: "Gastly", show: true },
  { value: "haunter", label: "Haunter", show: true },
  { value: "gengar", label: "Gengar", show: true },
  { value: "onix", label: "Onix", show: true },
  { value: "drowzee", label: "Drowzee", show: true },
  { value: "hypno", label: "Hypno", show: true },
  { value: "krabby", label: "Krabby", show: true },
  { value: "kingler", label: "Kingler", show: true },
  { value: "voltorb", label: "Voltorb", show: true },
  { value: "electrode", label: "Electrode", show: true },
  { value: "exeggcute", label: "Exeggcute", show: true },
  { value: "exeggutor", label: "Exeggutor", show: true },
  { value: "cubone", label: "Cubone", show: true },
  { value: "marowak", label: "Marowak", show: true },
  { value: "hitmonlee", label: "Hitmonlee", show: true },
  { value: "hitmonchan", label: "Hitmonchan", show: true },
  { value: "lickitung", label: "Lickitung", show: true },
  { value: "koffing", label: "Koffing", show: true },
  { value: "weezing", label: "Weezing", show: true },
  { value: "rhyhorn", label: "Rhyhorn", show: true },
  { value: "rhydon", label: "Rhydon", show: true },
  { value: "chansey", label: "Chansey", show: true },
  { value: "tangela", label: "Tangela", show: true },
  { value: "kangaskhan", label: "Kangaskhan", show: true },
  { value: "horsea", label: "Horsea", show: true },
  { value: "seadra", label: "Seadra", show: true },
  { value: "goldeen", label: "Goldeen", show: true },
  { value: "seaking", label: "Seaking", show: true },
  { value: "staryu", label: "Staryu", show: true },
  { value: "starmie", label: "Starmie", show: true },
  { value: "mr-mime", label: "Mr. Mime", show: true },
  { value: "scyther", label: "Scyther", show: true },
  { value: "jynx", label: "Jynx", show: true },
  { value: "electabuzz", label: "Electabuzz", show: true },
  { value: "magmar", label: "Magmar", show: true },
  { value: "pinsir", label: "Pinsir", show: true },
  { value: "tauros", label: "Tauros", show: true },
  { value: "magikarp", label: "Magikarp", show: true },
  { value: "gyarados", label: "Gyarados", show: true },
  { value: "lapras", label: "Lapras", show: true },
  { value: "ditto", label: "Ditto", show: true },
  { value: "eevee", label: "Eevee", show: true },
  { value: "vaporeon", label: "Vaporeon", show: true },
  { value: "jolteon", label: "Jolteon", show: true },
  { value: "flareon", label: "Flareon", show: true },
  { value: "porygon", label: "Porygon", show: true },
  { value: "omanyte", label: "Omanyte", show: true },
  { value: "omastar", label: "Omastar", show: true },
  { value: "kabuto", label: "Kabuto", show: true },
  { value: "kabutops", label: "Kabutops", show: true },
  { value: "aerodactyl", label: "Aerodactyl", show: true },
  { value: "snorlax", label: "Snorlax", show: true },
  { value: "articuno", label: "Articuno", show: true },
  { value: "zapdos", label: "Zapdos", show: true },
  { value: "moltres", label: "Moltres", show: true },
  { value: "dratini", label: "Dratini", show: true },
  { value: "dragonair", label: "Dragonair", show: true },
  { value: "dragonite", label: "Dragonite", show: true },
  { value: "mewtwo", label: "Mewtwo", show: true },
  { value: "mew", label: "Mew", show: true },
  { value: "chikorita", label: "Chikorita", show: true },
  { value: "bayleef", label: "Bayleef", show: true },
  { value: "meganium", label: "Meganium", show: true },
  { value: "cyndaquil", label: "Cyndaquil", show: true },
  { value: "quilava", label: "Quilava", show: true },
  { value: "typhlosion", label: "Typhlosion", show: true },
  { value: "totodile", label: "Totodile", show: true },
  { value: "croconaw", label: "Croconaw", show: true },
  { value: "feraligatr", label: "Feraligatr", show: true },
  { value: "sentret", label: "Sentret", show: true },
  { value: "furret", label: "Furret", show: true },
  { value: "hoothoot", label: "Hoothoot", show: true },
  { value: "noctowl", label: "Noctowl", show: true },
  { value: "ledyba", label: "Ledyba", show: true },
  { value: "ledian", label: "Ledian", show: true },
  { value: "spinarak", label: "Spinarak", show: true },
  { value: "ariados", label: "Ariados", show: true },
  { value: "crobat", label: "Crobat", show: true },
  { value: "chinchou", label: "Chinchou", show: true },
  { value: "lanturn", label: "Lanturn", show: true },
  { value: "pichu", label: "Pichu", show: true },
  { value: "cleffa", label: "Cleffa", show: true },
  { value: "igglybuff", label: "Igglybuff", show: true },
  { value: "togepi", label: "Togepi", show: true },
  { value: "togetic", label: "Togetic", show: true },
  { value: "natu", label: "Natu", show: true },
  { value: "xatu", label: "Xatu", show: true },
  { value: "mareep", label: "Mareep", show: true },
  { value: "flaaffy", label: "Flaaffy", show: true },
  { value: "ampharos", label: "Ampharos", show: true },
  { value: "bellossom", label: "Bellossom", show: true },
  { value: "marill", label: "Marill", show: true },
  { value: "azumarill", label: "Azumarill", show: true },
  { value: "sudowoodo", label: "Sudowoodo", show: true },
  { value: "politoed", label: "Politoed", show: true },
  { value: "hoppip", label: "Hoppip", show: true },
  { value: "skiploom", label: "Skiploom", show: true },
  { value: "jumpluff", label: "Jumpluff", show: true },
  { value: "aipom", label: "Aipom", show: true },
  { value: "sunkern", label: "Sunkern", show: true },
  { value: "sunflora", label: "Sunflora", show: true },
  { value: "yanma", label: "Yanma", show: true },
  { value: "wooper", label: "Wooper", show: true },
  { value: "quagsire", label: "Quagsire", show: true },
  { value: "espeon", label: "Espeon", show: true },
  { value: "umbreon", label: "Umbreon", show: true },
  { value: "murkrow", label: "Murkrow", show: true },
  { value: "slowking", label: "Slowking", show: true },
  { value: "misdreavus", label: "Misdreavus", show: true },
  { value: "unown", label: "Unown", show: true },
  { value: "wobbuffet", label: "Wobbuffet", show: true },
  { value: "girafarig", label: "Girafarig", show: true },
  { value: "pineco", label: "Pineco", show: true },
  { value: "forretress", label: "Forretress", show: true },
  { value: "dunsparce", label: "Dunsparce", show: true },
  { value: "gligar", label: "Gligar", show: true },
  { value: "steelix", label: "Steelix", show: true },
  { value: "snubbull", label: "Snubbull", show: true },
  { value: "granbull", label: "Granbull", show: true },
  { value: "qwilfish", label: "Qwilfish", show: true },
  { value: "scizor", label: "Scizor", show: true },
  { value: "shuckle", label: "Shuckle", show: true },
  { value: "heracross", label: "Heracross", show: true },
  { value: "sneasel", label: "Sneasel", show: true },
  { value: "teddiursa", label: "Teddiursa", show: true },
  { value: "ursaring", label: "Ursaring", show: true },
  { value: "slugma", label: "Slugma", show: true },
  { value: "magcargo", label: "Magcargo", show: true },
  { value: "swinub", label: "Swinub", show: true },
  { value: "piloswine", label: "Piloswine", show: true },
  { value: "corsola", label: "Corsola", show: true },
  { value: "remoraid", label: "Remoraid", show: true },
  { value: "octillery", label: "Octillery", show: true },
  { value: "delibird", label: "Delibird", show: true },
  { value: "mantine", label: "Mantine", show: true },
  { value: "skarmory", label: "Skarmory", show: true },
  { value: "houndour", label: "Houndour", show: true },
  { value: "houndoom", label: "Houndoom", show: true },
  { value: "kingdra", label: "Kingdra", show: true },
  { value: "phanpy", label: "Phanpy", show: true },
  { value: "donphan", label: "Donphan", show: true },
  { value: "porygon2", label: "Porygon2", show: true },
  { value: "stantler", label: "Stantler", show: true },
  { value: "smeargle", label: "Smeargle", show: true },
  { value: "tyrogue", label: "Tyrogue", show: true },
  { value: "hitmontop", label: "Hitmontop", show: true },
  { value: "smoochum", label: "Smoochum", show: true },
  { value: "elekid", label: "Elekid", show: true },
  { value: "magby", label: "Magby", show: true },
  { value: "miltank", label: "Miltank", show: true },
  { value: "blissey", label: "Blissey", show: true },
  { value: "raikou", label: "Raikou", show: true },
  { value: "entei", label: "Entei", show: true },
  { value: "suicune", label: "Suicune", show: true },
  { value: "larvitar", label: "Larvitar", show: true },
  { value: "pupitar", label: "Pupitar", show: true },
  { value: "tyranitar", label: "Tyranitar", show: true },
  { value: "lugia", label: "Lugia", show: true },
  { value: "ho-oh", label: "Ho-Oh", show: true },
  { value: "celebi", label: "Celebi", show: true },
  { value: "treecko", label: "Treecko", show: true },
  { value: "grovyle", label: "Grovyle", show: true },
  { value: "sceptile", label: "Sceptile", show: true },
  { value: "torchic", label: "Torchic", show: true },
  { value: "combusken", label: "Combusken", show: true },
  { value: "blaziken", label: "Blaziken", show: true },
  { value: "mudkip", label: "Mudkip", show: true },
  { value: "marshtomp", label: "Marshtomp", show: true },
  { value: "swampert", label: "Swampert", show: true },
  { value: "poochyena", label: "Poochyena", show: true },
  { value: "mightyena", label: "Mightyena", show: true },
  { value: "zigzagoon", label: "Zigzagoon", show: true },
  { value: "linoone", label: "Linoone", show: true },
  { value: "wurmple", label: "Wurmple", show: true },
  { value: "silcoon", label: "Silcoon", show: true },
  { value: "beautifly", label: "Beautifly", show: true },
  { value: "cascoon", label: "Cascoon", show: true },
  { value: "dustox", label: "Dustox", show: true },
  { value: "lotad", label: "Lotad", show: true },
  { value: "lombre", label: "Lombre", show: true },
  { value: "ludicolo", label: "Ludicolo", show: true },
  { value: "seedot", label: "Seedot", show: true },
  { value: "nuzleaf", label: "Nuzleaf", show: true },
  { value: "shiftry", label: "Shiftry", show: true },
  { value: "taillow", label: "Taillow", show: true },
  { value: "swellow", label: "Swellow", show: true },
  { value: "wingull", label: "Wingull", show: true },
  { value: "pelipper", label: "Pelipper", show: true },
  { value: "ralts", label: "Ralts", show: true },
  { value: "kirlia", label: "Kirlia", show: true },
  { value: "gardevoir", label: "Gardevoir", show: true },
  { value: "surskit", label: "Surskit", show: true },
  { value: "masquerain", label: "Masquerain", show: true },
  { value: "shroomish", label: "Shroomish", show: true },
  { value: "breloom", label: "Breloom", show: true },
  { value: "slakoth", label: "Slakoth", show: true },
  { value: "vigoroth", label: "Vigoroth", show: true },
  { value: "slaking", label: "Slaking", show: true },
  { value: "nincada", label: "Nincada", show: true },
  { value: "ninjask", label: "Ninjask", show: true },
  { value: "shedinja", label: "Shedinja", show: true },
  { value: "whismur", label: "Whismur", show: true },
  { value: "loudred", label: "Loudred", show: true },
  { value: "exploud", label: "Exploud", show: true },
  { value: "makuhita", label: "Makuhita", show: true },
  { value: "hariyama", label: "Hariyama", show: true },
  { value: "azurill", label: "Azurill", show: true },
  { value: "nosepass", label: "Nosepass", show: true },
  { value: "skitty", label: "Skitty", show: true },
  { value: "delcatty", label: "Delcatty", show: true },
  { value: "sableye", label: "Sableye", show: true },
  { value: "mawile", label: "Mawile", show: true },
  { value: "aron", label: "Aron", show: true },
  { value: "lairon", label: "Lairon", show: true },
  { value: "aggron", label: "Aggron", show: true },
  { value: "meditite", label: "Meditite", show: true },
  { value: "medicham", label: "Medicham", show: true },
  { value: "electrike", label: "Electrike", show: true },
  { value: "manectric", label: "Manectric", show: true },
  { value: "plusle", label: "Plusle", show: true },
  { value: "minun", label: "Minun", show: true },
  { value: "volbeat", label: "Volbeat", show: true },
  { value: "illumise", label: "Illumise", show: true },
  { value: "roselia", label: "Roselia", show: true },
  { value: "gulpin", label: "Gulpin", show: true },
  { value: "swalot", label: "Swalot", show: true },
  { value: "carvanha", label: "Carvanha", show: true },
  { value: "sharpedo", label: "Sharpedo", show: true },
  { value: "wailmer", label: "Wailmer", show: true },
  { value: "wailord", label: "Wailord", show: true },
  { value: "numel", label: "Numel", show: true },
  { value: "camerupt", label: "Camerupt", show: true },
  { value: "torkoal", label: "Torkoal", show: true },
  { value: "spoink", label: "Spoink", show: true },
  { value: "grumpig", label: "Grumpig", show: true },
  { value: "spinda", label: "Spinda", show: true },
  { value: "trapinch", label: "Trapinch", show: true },
  { value: "vibrava", label: "Vibrava", show: true },
  { value: "flygon", label: "Flygon", show: true },
  { value: "cacnea", label: "Cacnea", show: true },
  { value: "cacturne", label: "Cacturne", show: true },
  { value: "swablu", label: "Swablu", show: true },
  { value: "altaria", label: "Altaria", show: true },
  { value: "zangoose", label: "Zangoose", show: true },
  { value: "seviper", label: "Seviper", show: true },
  { value: "lunatone", label: "Lunatone", show: true },
  { value: "solrock", label: "Solrock", show: true },
  { value: "barboach", label: "Barboach", show: true },
  { value: "whiscash", label: "Whiscash", show: true },
  { value: "corphish", label: "Corphish", show: true },
  { value: "crawdaunt", label: "Crawdaunt", show: true },
  { value: "baltoy", label: "Baltoy", show: true },
  { value: "claydol", label: "Claydol", show: true },
  { value: "lileep", label: "Lileep", show: true },
  { value: "cradily", label: "Cradily", show: true },
  { value: "anorith", label: "Anorith", show: true },
  { value: "armaldo", label: "Armaldo", show: true },
  { value: "feebas", label: "Feebas", show: true },
  { value: "milotic", label: "Milotic", show: true },
  { value: "castform", label: "Castform", show: true },
  { value: "kecleon", label: "Kecleon", show: true },
  { value: "shuppet", label: "Shuppet", show: true },
  { value: "banette", label: "Banette", show: true },
  { value: "duskull", label: "Duskull", show: true },
  { value: "dusclops", label: "Dusclops", show: true },
  { value: "tropius", label: "Tropius", show: true },
  { value: "chimecho", label: "Chimecho", show: true },
  { value: "absol", label: "Absol", show: true },
  { value: "wynaut", label: "Wynaut", show: true },
  { value: "snorunt", label: "Snorunt", show: true },
  { value: "glalie", label: "Glalie", show: true },
  { value: "spheal", label: "Spheal", show: true },
  { value: "sealeo", label: "Sealeo", show: true },
  { value: "walrein", label: "Walrein", show: true },
  { value: "clamperl", label: "Clamperl", show: true },
  { value: "huntail", label: "Huntail", show: true },
  { value: "gorebyss", label: "Gorebyss", show: true },
  { value: "relicanth", label: "Relicanth", show: true },
  { value: "luvdisc", label: "Luvdisc", show: true },
  { value: "bagon", label: "Bagon", show: true },
  { value: "shelgon", label: "Shelgon", show: true },
  { value: "salamence", label: "Salamence", show: true },
  { value: "beldum", label: "Beldum", show: true },
  { value: "metang", label: "Metang", show: true },
  { value: "metagross", label: "Metagross", show: true },
  { value: "regirock", label: "Regirock", show: true },
  { value: "regice", label: "Regice", show: true },
  { value: "registeel", label: "Registeel", show: true },
  { value: "latias", label: "Latias", show: true },
  { value: "latios", label: "Latios", show: true },
  { value: "kyogre", label: "Kyogre", show: true },
  { value: "groudon", label: "Groudon", show: true },
  { value: "rayquaza", label: "Rayquaza", show: true },
  { value: "jirachi", label: "Jirachi", show: true },
  { value: "deoxys", label: "Deoxys", show: true },
  { value: "turtwig", label: "Turtwig", show: true },
  { value: "grotle", label: "Grotle", show: true },
  { value: "torterra", label: "Torterra", show: true },
  { value: "chimchar", label: "Chimchar", show: true },
  { value: "monferno", label: "Monferno", show: true },
  { value: "infernape", label: "Infernape", show: true },
  { value: "piplup", label: "Piplup", show: true },
  { value: "prinplup", label: "Prinplup", show: true },
  { value: "empoleon", label: "Empoleon", show: true },
  { value: "starly", label: "Starly", show: true },
  { value: "staravia", label: "Staravia", show: true },
  { value: "staraptor", label: "Staraptor", show: true },
  { value: "bidoof", label: "Bidoof", show: true },
  { value: "bibarel", label: "Bibarel", show: true },
  { value: "kricketot", label: "Kricketot", show: true },
  { value: "kricketune", label: "Kricketune", show: true },
  { value: "shinx", label: "Shinx", show: true },
  { value: "luxio", label: "Luxio", show: true },
  { value: "luxray", label: "Luxray", show: true },
  { value: "budew", label: "Budew", show: true },
  { value: "roserade", label: "Roserade", show: true },
  { value: "cranidos", label: "Cranidos", show: true },
  { value: "rampardos", label: "Rampardos", show: true },
  { value: "shieldon", label: "Shieldon", show: true },
  { value: "bastiodon", label: "Bastiodon", show: true },
  { value: "burmy", label: "Burmy", show: true },
  { value: "wormadam", label: "Wormadam", show: true },
  { value: "mothim", label: "Mothim", show: true },
  { value: "combee", label: "Combee", show: true },
  { value: "vespiquen", label: "Vespiquen", show: true },
  { value: "pachirisu", label: "Pachirisu", show: true },
  { value: "buizel", label: "Buizel", show: true },
  { value: "floatzel", label: "Floatzel", show: true },
  { value: "cherubi", label: "Cherubi", show: true },
  { value: "cherrim", label: "Cherrim", show: true },
  { value: "shellos", label: "Shellos", show: true },
  { value: "gastrodon", label: "Gastrodon", show: true },
  { value: "ambipom", label: "Ambipom", show: true },
  { value: "drifloon", label: "Drifloon", show: true },
  { value: "drifblim", label: "Drifblim", show: true },
  { value: "buneary", label: "Buneary", show: true },
  { value: "lopunny", label: "Lopunny", show: true },
  { value: "mismagius", label: "Mismagius", show: true },
  { value: "honchkrow", label: "Honchkrow", show: true },
  { value: "glameow", label: "Glameow", show: true },
  { value: "purugly", label: "Purugly", show: true },
  { value: "chingling", label: "Chingling", show: true },
  { value: "stunky", label: "Stunky", show: true },
  { value: "skuntank", label: "Skuntank", show: true },
  { value: "bronzor", label: "Bronzor", show: true },
  { value: "bronzong", label: "Bronzong", show: true },
  { value: "bonsly", label: "Bonsly", show: true },
  { value: "mime-jr", label: "Mime Jr.", show: true },
  { value: "happiny", label: "Happiny", show: true },
  { value: "chatot", label: "Chatot", show: true },
  { value: "spiritomb", label: "Spiritomb", show: true },
  { value: "gible", label: "Gible", show: true },
  { value: "gabite", label: "Gabite", show: true },
  { value: "garchomp", label: "Garchomp", show: true },
  { value: "munchlax", label: "Munchlax", show: true },
  { value: "riolu", label: "Riolu", show: true },
  { value: "lucario", label: "Lucario", show: true },
  { value: "hippopotas", label: "Hippopotas", show: true },
  { value: "hippowdon", label: "Hippowdon", show: true },
  { value: "skorupi", label: "Skorupi", show: true },
  { value: "drapion", label: "Drapion", show: true },
  { value: "croagunk", label: "Croagunk", show: true },
  { value: "toxicroak", label: "Toxicroak", show: true },
  { value: "carnivine", label: "Carnivine", show: true },
  { value: "finneon", label: "Finneon", show: true },
  { value: "lumineon", label: "Lumineon", show: true },
  { value: "mantyke", label: "Mantyke", show: true },
  { value: "snover", label: "Snover", show: true },
  { value: "abomasnow", label: "Abomasnow", show: true },
  { value: "weavile", label: "Weavile", show: true },
  { value: "magnezone", label: "Magnezone", show: true },
  { value: "lickilicky", label: "Lickilicky", show: true },
  { value: "rhyperior", label: "Rhyperior", show: true },
  { value: "tangrowth", label: "Tangrowth", show: true },
  { value: "electivire", label: "Electivire", show: true },
  { value: "magmortar", label: "Magmortar", show: true },
  { value: "togekiss", label: "Togekiss", show: true },
  { value: "yanmega", label: "Yanmega", show: true },
  { value: "leafeon", label: "Leafeon", show: true },
  { value: "glaceon", label: "Glaceon", show: true },
  { value: "gliscor", label: "Gliscor", show: true },
  { value: "mamoswine", label: "Mamoswine", show: true },
  { value: "porygon-z", label: "Porygon-Z", show: true },
  { value: "gallade", label: "Gallade", show: true },
  { value: "probopass", label: "Probopass", show: true },
  { value: "dusknoir", label: "Dusknoir", show: true },
  { value: "froslass", label: "Froslass", show: true },
  { value: "rotom", label: "Rotom", show: true },
  { value: "uxie", label: "Uxie", show: true },
  { value: "mesprit", label: "Mesprit", show: true },
  { value: "azelf", label: "Azelf", show: true },
  { value: "dialga", label: "Dialga", show: true },
  { value: "palkia", label: "Palkia", show: true },
  { value: "heatran", label: "Heatran", show: true },
  { value: "regigigas", label: "Regigigas", show: true },
  { value: "giratina", label: "Giratina", show: true },
  { value: "cresselia", label: "Cresselia", show: true },
  { value: "phione", label: "Phione", show: true },
  { value: "manaphy", label: "Manaphy", show: true },
  { value: "darkrai", label: "Darkrai", show: true },
  { value: "shaymin", label: "Shaymin", show: true },
  { value: "arceus", label: "Arceus", show: true },
  { value: "victini", label: "Victini", show: true },
  { value: "snivy", label: "Snivy", show: true },
  { value: "servine", label: "Servine", show: true },
  { value: "serperior", label: "Serperior", show: true },
  { value: "tepig", label: "Tepig", show: true },
  { value: "pignite", label: "Pignite", show: true },
  { value: "emboar", label: "Emboar", show: true },
  { value: "oshawott", label: "Oshawott", show: true },
  { value: "dewott", label: "Dewott", show: true },
  { value: "samurott", label: "Samurott", show: true },
  { value: "patrat", label: "Patrat", show: true },
  { value: "watchog", label: "Watchog", show: true },
  { value: "lillipup", label: "Lillipup", show: true },
  { value: "herdier", label: "Herdier", show: true },
  { value: "stoutland", label: "Stoutland", show: true },
  { value: "purrloin", label: "Purrloin", show: true },
  { value: "liepard", label: "Liepard", show: true },
  { value: "pansage", label: "Pansage", show: true },
  { value: "simisage", label: "Simisage", show: true },
  { value: "pansear", label: "Pansear", show: true },
  { value: "simisear", label: "Simisear", show: true },
  { value: "panpour", label: "Panpour", show: true },
  { value: "simipour", label: "Simipour", show: true },
  { value: "munna", label: "Munna", show: true },
  { value: "musharna", label: "Musharna", show: true },
  { value: "pidove", label: "Pidove", show: true },
  { value: "tranquill", label: "Tranquill", show: true },
  { value: "unfezant", label: "Unfezant", show: true },
  { value: "blitzle", label: "Blitzle", show: true },
  { value: "zebstrika", label: "Zebstrika", show: true },
  { value: "roggenrola", label: "Roggenrola", show: true },
  { value: "boldore", label: "Boldore", show: true },
  { value: "gigalith", label: "Gigalith", show: true },
  { value: "woobat", label: "Woobat", show: true },
  { value: "swoobat", label: "Swoobat", show: true },
  { value: "drilbur", label: "Drilbur", show: true },
  { value: "excadrill", label: "Excadrill", show: true },
  { value: "audino", label: "Audino", show: true },
  { value: "timburr", label: "Timburr", show: true },
  { value: "gurdurr", label: "Gurdurr", show: true },
  { value: "conkeldurr", label: "Conkeldurr", show: true },
  { value: "tympole", label: "Tympole", show: true },
  { value: "palpitoad", label: "Palpitoad", show: true },
  { value: "seismitoad", label: "Seismitoad", show: true },
  { value: "throh", label: "Throh", show: true },
  { value: "sawk", label: "Sawk", show: true },
  { value: "sewaddle", label: "Sewaddle", show: true },
  { value: "swadloon", label: "Swadloon", show: true },
  { value: "leavanny", label: "Leavanny", show: true },
  { value: "venipede", label: "Venipede", show: true },
  { value: "whirlipede", label: "Whirlipede", show: true },
  { value: "scolipede", label: "Scolipede", show: true },
  { value: "cottonee", label: "Cottonee", show: true },
  { value: "whimsicott", label: "Whimsicott", show: true },
  { value: "petilil", label: "Petilil", show: true },
  { value: "lilligant", label: "Lilligant", show: true },
  { value: "basculin", label: "Basculin", show: true },
  { value: "sandile", label: "Sandile", show: true },
  { value: "krokorok", label: "Krokorok", show: true },
  { value: "krookodile", label: "Krookodile", show: true },
  { value: "darumaka", label: "Darumaka", show: true },
  { value: "darmanitan", label: "Darmanitan", show: true },
  { value: "maractus", label: "Maractus", show: true },
  { value: "dwebble", label: "Dwebble", show: true },
  { value: "crustle", label: "Crustle", show: true },
  { value: "scraggy", label: "Scraggy", show: true },
  { value: "scrafty", label: "Scrafty", show: true },
  { value: "sigilyph", label: "Sigilyph", show: true },
  { value: "yamask", label: "Yamask", show: true },
  { value: "cofagrigus", label: "Cofagrigus", show: true },
  { value: "tirtouga", label: "Tirtouga", show: true },
  { value: "carracosta", label: "Carracosta", show: true },
  { value: "archen", label: "Archen", show: true },
  { value: "archeops", label: "Archeops", show: true },
  { value: "trubbish", label: "Trubbish", show: true },
  { value: "garbodor", label: "Garbodor", show: true },
  { value: "zorua", label: "Zorua", show: true },
  { value: "zoroark", label: "Zoroark", show: true },
  { value: "minccino", label: "Minccino", show: true },
  { value: "cinccino", label: "Cinccino", show: true },
  { value: "gothita", label: "Gothita", show: true },
  { value: "gothorita", label: "Gothorita", show: true },
  { value: "gothitelle", label: "Gothitelle", show: true },
  { value: "solosis", label: "Solosis", show: true },
  { value: "duosion", label: "Duosion", show: true },
  { value: "reuniclus", label: "Reuniclus", show: true },
  { value: "ducklett", label: "Ducklett", show: true },
  { value: "swanna", label: "Swanna", show: true },
  { value: "vanillite", label: "Vanillite", show: true },
  { value: "vanillish", label: "Vanillish", show: true },
  { value: "vanilluxe", label: "Vanilluxe", show: true },
  { value: "deerling", label: "Deerling", show: true },
  { value: "sawsbuck", label: "Sawsbuck", show: true },
  { value: "emolga", label: "Emolga", show: true },
  { value: "karrablast", label: "Karrablast", show: true },
  { value: "escavalier", label: "Escavalier", show: true },
  { value: "foongus", label: "Foongus", show: true },
  { value: "amoonguss", label: "Amoonguss", show: true },
  { value: "frillish", label: "Frillish", show: true },
  { value: "jellicent", label: "Jellicent", show: true },
  { value: "alomomola", label: "Alomomola", show: true },
  { value: "joltik", label: "Joltik", show: true },
  { value: "galvantula", label: "Galvantula", show: true },
  { value: "ferroseed", label: "Ferroseed", show: true },
  { value: "ferrothorn", label: "Ferrothorn", show: true },
  { value: "klink", label: "Klink", show: true },
  { value: "klang", label: "Klang", show: true },
  { value: "klinklang", label: "Klinklang", show: true },
  { value: "tynamo", label: "Tynamo", show: true },
  { value: "eelektrik", label: "Eelektrik", show: true },
  { value: "eelektross", label: "Eelektross", show: true },
  { value: "elgyem", label: "Elgyem", show: true },
  { value: "beheeyem", label: "Beheeyem", show: true },
  { value: "litwick", label: "Litwick", show: true },
  { value: "lampent", label: "Lampent", show: true },
  { value: "chandelure", label: "Chandelure", show: true },
  { value: "axew", label: "Axew", show: true },
  { value: "fraxure", label: "Fraxure", show: true },
  { value: "haxorus", label: "Haxorus", show: true },
  { value: "cubchoo", label: "Cubchoo", show: true },
  { value: "beartic", label: "Beartic", show: true },
  { value: "cryogonal", label: "Cryogonal", show: true },
  { value: "shelmet", label: "Shelmet", show: true },
  { value: "accelgor", label: "Accelgor", show: true },
  { value: "stunfisk", label: "Stunfisk", show: true },
  { value: "mienfoo", label: "Mienfoo", show: true },
  { value: "mienshao", label: "Mienshao", show: true },
  { value: "druddigon", label: "Druddigon", show: true },
  { value: "golett", label: "Golett", show: true },
  { value: "golurk", label: "Golurk", show: true },
  { value: "pawniard", label: "Pawniard", show: true },
  { value: "bisharp", label: "Bisharp", show: true },
  { value: "bouffalant", label: "Bouffalant", show: true },
  { value: "rufflet", label: "Rufflet", show: true },
  { value: "braviary", label: "Braviary", show: true },
  { value: "vullaby", label: "Vullaby", show: true },
  { value: "mandibuzz", label: "Mandibuzz", show: true },
  { value: "heatmor", label: "Heatmor", show: true },
  { value: "durant", label: "Durant", show: true },
  { value: "deino", label: "Deino", show: true },
  { value: "zweilous", label: "Zweilous", show: true },
  { value: "hydreigon", label: "Hydreigon", show: true },
  { value: "larvesta", label: "Larvesta", show: true },
  { value: "volcarona", label: "Volcarona", show: true },
  { value: "cobalion", label: "Cobalion", show: true },
  { value: "terrakion", label: "Terrakion", show: true },
  { value: "virizion", label: "Virizion", show: true },
  { value: "tornadus", label: "Tornadus", show: true },
  { value: "thundurus", label: "Thundurus", show: true },
  { value: "reshiram", label: "Reshiram", show: true },
  { value: "zekrom", label: "Zekrom", show: true },
  { value: "landorus", label: "Landorus", show: true },
  { value: "kyurem", label: "Kyurem", show: true },
  { value: "keldeo", label: "Keldeo", show: true },
  { value: "meloetta", label: "Meloetta", show: true },
  { value: "genesect", label: "Genesect", show: true },
  { value: "chespin", label: "Chespin", show: true },
  { value: "quilladin", label: "Quilladin", show: true },
  { value: "chesnaught", label: "Chesnaught", show: true },
  { value: "fennekin", label: "Fennekin", show: true },
  { value: "braixen", label: "Braixen", show: true },
  { value: "delphox", label: "Delphox", show: true },
  { value: "froakie", label: "Froakie", show: true },
  { value: "frogadier", label: "Frogadier", show: true },
  { value: "greninja", label: "Greninja", show: true },
  { value: "bunnelby", label: "Bunnelby", show: true },
  { value: "diggersby", label: "Diggersby", show: true },
  { value: "fletchling", label: "Fletchling", show: true },
  { value: "fletchinder", label: "Fletchinder", show: true },
  { value: "talonflame", label: "Talonflame", show: true },
  { value: "scatterbug", label: "Scatterbug", show: true },
  { value: "spewpa", label: "Spewpa", show: true },
  { value: "vivillon", label: "Vivillon", show: true },
  { value: "litleo", label: "Litleo", show: true },
  { value: "pyroar", label: "Pyroar", show: true },
  { value: "flabebe", label: "FlabÃ©bÃ©", show: true },
  { value: "floette", label: "Floette", show: true },
  { value: "florges", label: "Florges", show: true },
  { value: "skiddo", label: "Skiddo", show: true },
  { value: "gogoat", label: "Gogoat", show: true },
  { value: "pancham", label: "Pancham", show: true },
  { value: "pangoro", label: "Pangoro", show: true },
  { value: "furfrou", label: "Furfrou", show: true },
  { value: "espurr", label: "Espurr", show: true },
  { value: "meowstic", label: "Meowstic", show: true },
  { value: "honedge", label: "Honedge", show: true },
  { value: "doublade", label: "Doublade", show: true },
  { value: "aegislash", label: "Aegislash", show: true },
  { value: "spritzee", label: "Spritzee", show: true },
  { value: "aromatisse", label: "Aromatisse", show: true },
  { value: "swirlix", label: "Swirlix", show: true },
  { value: "slurpuff", label: "Slurpuff", show: true },
  { value: "inkay", label: "Inkay", show: true },
  { value: "malamar", label: "Malamar", show: true },
  { value: "binacle", label: "Binacle", show: true },
  { value: "barbaracle", label: "Barbaracle", show: true },
  { value: "skrelp", label: "Skrelp", show: true },
  { value: "dragalge", label: "Dragalge", show: true },
  { value: "clauncher", label: "Clauncher", show: true },
  { value: "clawitzer", label: "Clawitzer", show: true },
  { value: "helioptile", label: "Helioptile", show: true },
  { value: "heliolisk", label: "Heliolisk", show: true },
  { value: "tyrunt", label: "Tyrunt", show: true },
  { value: "tyrantrum", label: "Tyrantrum", show: true },
  { value: "amaura", label: "Amaura", show: true },
  { value: "aurorus", label: "Aurorus", show: true },
  { value: "sylveon", label: "Sylveon", show: true },
  { value: "hawlucha", label: "Hawlucha", show: true },
  { value: "dedenne", label: "Dedenne", show: true },
  { value: "carbink", label: "Carbink", show: true },
  { value: "goomy", label: "Goomy", show: true },
  { value: "sliggoo", label: "Sliggoo", show: true },
  { value: "goodra", label: "Goodra", show: true },
  { value: "klefki", label: "Klefki", show: true },
  { value: "phantump", label: "Phantump", show: true },
  { value: "trevenant", label: "Trevenant", show: true },
  { value: "pumpkaboo", label: "Pumpkaboo", show: true },
  { value: "gourgeist", label: "Gourgeist", show: true },
  { value: "bergmite", label: "Bergmite", show: true },
  { value: "avalugg", label: "Avalugg", show: true },
  { value: "noibat", label: "Noibat", show: true },
  { value: "noivern", label: "Noivern", show: true },
  { value: "xerneas", label: "Xerneas", show: true },
  { value: "yveltal", label: "Yveltal", show: true },
  { value: "zygarde", label: "Zygarde", show: true },
  { value: "diancie", label: "Diancie", show: true },
  { value: "hoopa", label: "Hoopa", show: true },
  { value: "volcanion", label: "Volcanion", show: true },
  { value: "rowlet", label: "Rowlet", show: true },
  { value: "dartrix", label: "Dartrix", show: true },
  { value: "decidueye", label: "Decidueye", show: true },
  { value: "litten", label: "Litten", show: true },
  { value: "torracat", label: "Torracat", show: true },
  { value: "incineroar", label: "Incineroar", show: true },
  { value: "popplio", label: "Popplio", show: true },
  { value: "brionne", label: "Brionne", show: true },
  { value: "primarina", label: "Primarina", show: true },
  { value: "pikipek", label: "Pikipek", show: true },
  { value: "trumbeak", label: "Trumbeak", show: true },
  { value: "toucannon", label: "Toucannon", show: true },
  { value: "yungoos", label: "Yungoos", show: true },
  { value: "gumshoos", label: "Gumshoos", show: true },
  { value: "grubbin", label: "Grubbin", show: true },
  { value: "charjabug", label: "Charjabug", show: true },
  { value: "vikavolt", label: "Vikavolt", show: true },
  { value: "crabrawler", label: "Crabrawler", show: true },
  { value: "crabominable", label: "Crabominable", show: true },
  { value: "oricorio", label: "Oricorio", show: true },
  { value: "cutiefly", label: "Cutiefly", show: true },
  { value: "ribombee", label: "Ribombee", show: true },
  { value: "rockruff", label: "Rockruff", show: true },
  { value: "lycanroc", label: "Lycanroc", show: true },
  { value: "wishiwashi", label: "Wishiwashi", show: true },
  { value: "mareanie", label: "Mareanie", show: true },
  { value: "toxapex", label: "Toxapex", show: true },
  { value: "mudbray", label: "Mudbray", show: true },
  { value: "mudsdale", label: "Mudsdale", show: true },
  { value: "dewpider", label: "Dewpider", show: true },
  { value: "araquanid", label: "Araquanid", show: true },
  { value: "fomantis", label: "Fomantis", show: true },
  { value: "lurantis", label: "Lurantis", show: true },
  { value: "morelull", label: "Morelull", show: true },
  { value: "shiinotic", label: "Shiinotic", show: true },
  { value: "salandit", label: "Salandit", show: true },
  { value: "salazzle", label: "Salazzle", show: true },
  { value: "stufful", label: "Stufful", show: true },
  { value: "bewear", label: "Bewear", show: true },
  { value: "bounsweet", label: "Bounsweet", show: true },
  { value: "steenee", label: "Steenee", show: true },
  { value: "tsareena", label: "Tsareena", show: true },
  { value: "comfey", label: "Comfey", show: true },
  { value: "oranguru", label: "Oranguru", show: true },
  { value: "passimian", label: "Passimian", show: true },
  { value: "wimpod", label: "Wimpod", show: true },
  { value: "golisopod", label: "Golisopod", show: true },
  { value: "sandygast", label: "Sandygast", show: true },
  { value: "palossand", label: "Palossand", show: true },
  { value: "pyukumuku", label: "Pyukumuku", show: true },
  { value: "type-null", label: "Type: Null", show: true },
  { value: "silvally", label: "Silvally", show: true },
  { value: "minior", label: "Minior", show: true },
  { value: "komala", label: "Komala", show: true },
  { value: "turtonator", label: "Turtonator", show: true },
  { value: "togedemaru", label: "Togedemaru", show: true },
  { value: "mimikyu", label: "Mimikyu", show: true },
  { value: "bruxish", label: "Bruxish", show: true },
  { value: "drampa", label: "Drampa", show: true },
  { value: "dhelmise", label: "Dhelmise", show: true },
  { value: "jangmo-o", label: "Jangmo-o", show: true },
  { value: "hakamo-o", label: "Hakamo-o", show: true },
  { value: "kommo-o", label: "Kommo-o", show: true },
  { value: "tapu-koko", label: "Tapu Koko", show: true },
  { value: "tapu-lele", label: "Tapu Lele", show: true },
  { value: "tapu-bulu", label: "Tapu Bulu", show: true },
  { value: "tapu-fini", label: "Tapu Fini", show: true },
  { value: "cosmog", label: "Cosmog", show: true },
  { value: "cosmoem", label: "Cosmoem", show: true },
  { value: "solgaleo", label: "Solgaleo", show: true },
  { value: "lunala", label: "Lunala", show: true },
  { value: "nihilego", label: "Nihilego", show: true },
  { value: "buzzwole", label: "Buzzwole", show: true },
  { value: "pheromosa", label: "Pheromosa", show: true },
  { value: "xurkitree", label: "Xurkitree", show: true },
  { value: "celesteela", label: "Celesteela", show: true },
  { value: "kartana", label: "Kartana", show: true },
  { value: "guzzlord", label: "Guzzlord", show: true },
  { value: "necrozma", label: "Necrozma", show: true },
  { value: "magearna", label: "Magearna", show: true },
  { value: "marshadow", label: "Marshadow", show: true },
  { value: "poipole", label: "Poipole", show: true },
  { value: "naganadel", label: "Naganadel", show: true },
  { value: "stakataka", label: "Stakataka", show: true },
  { value: "blacephalon", label: "Blacephalon", show: true },
  { value: "zeraora", label: "Zeraora", show: true },
  { value: "meltan", label: "Meltan", show: true },
  { value: "melmetal", label: "Melmetal", show: true },
  { value: "grookey", label: "Grookey", show: true },
  { value: "thwackey", label: "Thwackey", show: true },
  { value: "rillaboom", label: "Rillaboom", show: true },
  { value: "scorbunny", label: "Scorbunny", show: true },
  { value: "raboot", label: "Raboot", show: true },
  { value: "cinderace", label: "Cinderace", show: true },
  { value: "sobble", label: "Sobble", show: true },
  { value: "drizzile", label: "Drizzile", show: true },
  { value: "inteleon", label: "Inteleon", show: true },
  { value: "skwovet", label: "Skwovet", show: true },
  { value: "greedent", label: "Greedent", show: true },
  { value: "rookidee", label: "Rookidee", show: true },
  { value: "corvisquire", label: "Corvisquire", show: true },
  { value: "corviknight", label: "Corviknight", show: true },
  { value: "blipbug", label: "Blipbug", show: true },
  { value: "dottler", label: "Dottler", show: true },
  { value: "orbeetle", label: "Orbeetle", show: true },
  { value: "nickit", label: "Nickit", show: true },
  { value: "thievul", label: "Thievul", show: true },
  { value: "gossifleur", label: "Gossifleur", show: true },
  { value: "eldegoss", label: "Eldegoss", show: true },
  { value: "wooloo", label: "Wooloo", show: true },
  { value: "dubwool", label: "Dubwool", show: true },
  { value: "chewtle", label: "Chewtle", show: true },
  { value: "drednaw", label: "Drednaw", show: true },
  { value: "yamper", label: "Yamper", show: true },
  { value: "boltund", label: "Boltund", show: true },
  { value: "rolycoly", label: "Rolycoly", show: true },
  { value: "carkol", label: "Carkol", show: true },
  { value: "coalossal", label: "Coalossal", show: true },
  { value: "applin", label: "Applin", show: true },
  { value: "flapple", label: "Flapple", show: true },
  { value: "appletun", label: "Appletun", show: true },
  { value: "silicobra", label: "Silicobra", show: true },
  { value: "sandaconda", label: "Sandaconda", show: true },
  { value: "cramorant", label: "Cramorant", show: true },
  { value: "arrokuda", label: "Arrokuda", show: true },
  { value: "barraskewda", label: "Barraskewda", show: true },
  { value: "toxel", label: "Toxel", show: true },
  { value: "toxtricity", label: "Toxtricity", show: true },
  { value: "sizzlipede", label: "Sizzlipede", show: true },
  { value: "centiskorch", label: "Centiskorch", show: true },
  { value: "clobbopus", label: "Clobbopus", show: true },
  { value: "grapploct", label: "Grapploct", show: true },
  { value: "sinistea", label: "Sinistea", show: true },
  { value: "polteageist", label: "Polteageist", show: true },
  { value: "hatenna", label: "Hatenna", show: true },
  { value: "hattrem", label: "Hattrem", show: true },
  { value: "hatterene", label: "Hatterene", show: true },
  { value: "impidimp", label: "Impidimp", show: true },
  { value: "morgrem", label: "Morgrem", show: true },
  { value: "grimmsnarl", label: "Grimmsnarl", show: true },
  { value: "obstagoon", label: "Obstagoon", show: true },
  { value: "perrserker", label: "Perrserker", show: true },
  { value: "cursola", label: "Cursola", show: true },
  { value: "sirfetchd", label: "Sirfetch’d", show: true },
  { value: "mr-rime", label: "Mr. Rime", show: true },
  { value: "runerigus", label: "Runerigus", show: true },
  { value: "milcery", label: "Milcery", show: true },
  { value: "alcremie", label: "Alcremie", show: true },
  { value: "falinks", label: "Falinks", show: true },
  { value: "pincurchin", label: "Pincurchin", show: true },
  { value: "snom", label: "Snom", show: true },
  { value: "frosmoth", label: "Frosmoth", show: true },
  { value: "stonjourner", label: "Stonjourner", show: true },
  { value: "eiscue", label: "Eiscue", show: true },
  { value: "indeedee", label: "Indeedee", show: true },
  { value: "morpeko", label: "Morpeko", show: true },
  { value: "cufant", label: "Cufant", show: true },
  { value: "copperajah", label: "Copperajah", show: true },
  { value: "dracozolt", label: "Dracozolt", show: true },
  { value: "arctozolt", label: "Arctozolt", show: true },
  { value: "dracovish", label: "Dracovish", show: true },
  { value: "arctovish", label: "Arctovish", show: true },
  { value: "duraludon", label: "Duraludon", show: true },
  { value: "dreepy", label: "Dreepy", show: true },
  { value: "drakloak", label: "Drakloak", show: true },
  { value: "dragapult", label: "Dragapult", show: true },
  { value: "zacian", label: "Zacian", show: true },
  { value: "zamazenta", label: "Zamazenta", show: true },
  { value: "eternatus", label: "Eternatus", show: true },
  { value: "kubfu", label: "Kubfu", show: true },
  { value: "urshifu", label: "Urshifu", show: true },
  { value: "zarude", label: "Zarude", show: true },
  { value: "regieleki", label: "Regieleki", show: true },
  { value: "regidrago", label: "Regidrago", show: true },
  { value: "glastrier", label: "Glastrier", show: true },
  { value: "spectrier", label: "Spectrier", show: true },
  { value: "calyrex", label: "Calyrex", show: true },
  { value: "wyrdeer", label: "Wyrdeer", show: true },
  { value: "kleavor", label: "Kleavor", show: true },
  { value: "ursaluna", label: "Ursaluna", show: true },
  { value: "basculegion", label: "Basculegion", show: true },
  { value: "sneasler", label: "Sneasler", show: true },
  { value: "overqwil", label: "Overqwil", show: true },
  { value: "enamorus", label: "Enamorus", show: true },
  { value: "sprigatito", label: "Sprigatito", show: true },
  { value: "floragato", label: "Floragato", show: true },
  { value: "meowscarada", label: "Meowscarada", show: true },
  { value: "fuecoco", label: "Fuecoco", show: true },
  { value: "crocalor", label: "Crocalor", show: true },
  { value: "skeledirge", label: "Skeledirge", show: true },
  { value: "quaxly", label: "Quaxly", show: true },
  { value: "quaxwell", label: "Quaxwell", show: true },
  { value: "quaquaval", label: "Quaquaval", show: true },
  { value: "lechonk", label: "Lechonk", show: true },
  { value: "oinkologne", label: "Oinkologne", show: true },
  { value: "tarountula", label: "Tarountula", show: true },
  { value: "spidops", label: "Spidops", show: true },
  { value: "nymble", label: "Nymble", show: true },
  { value: "lokix", label: "Lokix", show: true },
  { value: "pawmi", label: "Pawmi", show: true },
  { value: "pawmo", label: "Pawmo", show: true },
  { value: "pawmot", label: "Pawmot", show: true },
  { value: "tandemaus", label: "Tandemaus", show: true },
  { value: "maushold", label: "Maushold", show: true },
  { value: "fidough", label: "Fidough", show: true },
  { value: "dachsbun", label: "Dachsbun", show: true },
  { value: "smoliv", label: "Smoliv", show: true },
  { value: "dolliv", label: "Dolliv", show: true },
  { value: "arboliva", label: "Arboliva", show: true },
  { value: "squawkabilly", label: "Squawkabilly", show: true },
  { value: "nacli", label: "Nacli", show: true },
  { value: "naclstack", label: "Naclstack", show: true },
  { value: "garganacl", label: "Garganacl", show: true },
  { value: "charcadet", label: "Charcadet", show: true },
  { value: "armarouge", label: "Armarouge", show: true },
  { value: "ceruledge", label: "Ceruledge", show: true },
  { value: "tadbulb", label: "Tadbulb", show: true },
  { value: "bellibolt", label: "Bellibolt", show: true },
  { value: "wattrel", label: "Wattrel", show: true },
  { value: "kilowattrel", label: "Kilowattrel", show: true },
  { value: "maschiff", label: "Maschiff", show: true },
  { value: "mabosstiff", label: "Mabosstiff", show: true },
  { value: "shroodle", label: "Shroodle", show: true },
  { value: "grafaiai", label: "Grafaiai", show: true },
  { value: "bramblin", label: "Bramblin", show: true },
  { value: "brambleghast", label: "Brambleghast", show: true },
  { value: "toedscool", label: "Toedscool", show: true },
  { value: "toedscruel", label: "Toedscruel", show: true },
  { value: "klawf", label: "Klawf", show: true },
  { value: "capsakid", label: "Capsakid", show: true },
  { value: "scovillain", label: "Scovillain", show: true },
  { value: "rellor", label: "Rellor", show: true },
  { value: "rabsca", label: "Rabsca", show: true },
  { value: "flittle", label: "Flittle", show: true },
  { value: "espathra", label: "Espathra", show: true },
  { value: "tinkatink", label: "Tinkatink", show: true },
  { value: "tinkatuff", label: "Tinkatuff", show: true },
  { value: "tinkaton", label: "Tinkaton", show: true },
  { value: "wiglett", label: "Wiglett", show: true },
  { value: "wugtrio", label: "Wugtrio", show: true },
  { value: "bombirdier", label: "Bombirdier", show: true },
  { value: "finizen", label: "Finizen", show: true },
  { value: "palafin", label: "Palafin", show: true },
  { value: "varoom", label: "Varoom", show: true },
  { value: "revavroom", label: "Revavroom", show: true },
  { value: "cyclizar", label: "Cyclizar", show: true },
  { value: "orthworm", label: "Orthworm", show: true },
  { value: "glimmet", label: "Glimmet", show: true },
  { value: "glimmora", label: "Glimmora", show: true },
  { value: "greavard", label: "Greavard", show: true },
  { value: "houndstone", label: "Houndstone", show: true },
  { value: "flamigo", label: "Flamigo", show: true },
  { value: "cetoddle", label: "Cetoddle", show: true },
  { value: "cetitan", label: "Cetitan", show: true },
  { value: "veluza", label: "Veluza", show: true },
  { value: "dondozo", label: "Dondozo", show: true },
  { value: "tatsugiri", label: "Tatsugiri", show: true },
  { value: "annihilape", label: "Annihilape", show: true },
  { value: "clodsire", label: "Clodsire", show: true },
  { value: "farigiraf", label: "Farigiraf", show: true },
  { value: "dudunsparce", label: "Dudunsparce", show: true },
  { value: "kingambit", label: "Kingambit", show: true },
  { value: "great-tusk", label: "Great Tusk", show: true },
  { value: "scream-tail", label: "Scream Tail", show: true },
  { value: "brute-bonnet", label: "Brute Bonnet", show: true },
  { value: "flutter-mane", label: "Flutter Mane", show: true },
  { value: "slither-wing", label: "Slither Wing", show: true },
  { value: "sandy-shocks", label: "Sandy Shocks", show: true },
  { value: "iron-treads", label: "Iron Treads", show: true },
  { value: "iron-bundle", label: "Iron Bundle", show: true },
  { value: "iron-hands", label: "Iron Hands", show: true },
  { value: "iron-jugulis", label: "Iron Jugulis", show: true },
  { value: "iron-moth", label: "Iron Moth", show: true },
  { value: "iron-thorns", label: "Iron Thorns", show: true },
  { value: "frigibax", label: "Frigibax", show: true },
  { value: "arctibax", label: "Arctibax", show: true },
  { value: "baxcalibur", label: "Baxcalibur", show: true },
  { value: "gimmighoul", label: "Gimmighoul", show: true },
  { value: "gholdengo", label: "Gholdengo", show: true },
  { value: "wo-chien", label: "Wo-Chien", show: true },
  { value: "chien-pao", label: "Chien-Pao", show: true },
  { value: "ting-lu", label: "Ting-Lu", show: true },
  { value: "chi-yu", label: "Chi-Yu", show: true },
  { value: "roaring-moon", label: "Roaring Moon", show: true },
  { value: "iron-valiant", label: "Iron Valiant", show: true },
  { value: "koraidon", label: "Koraidon", show: true },
  { value: "miraidon", label: "Miraidon", show: true },
  { value: "walking-wake", label: "Walking Wake", show: true },
  { value: "iron-leaves", label: "Iron Leaves", show: true },
  { value: "dipplin", label: "Dipplin", show: true },
  { value: "poltchageist", label: "Poltchageist", show: true },
  { value: "sinistcha", label: "Sinistcha", show: true },
  { value: "okidogi", label: "Okidogi", show: true },
  { value: "munkidori", label: "Munkidori", show: true },
  { value: "fezandipiti", label: "Fezandipiti", show: true },
  { value: "ogerpon", label: "Ogerpon", show: true },
  { value: "archaludon", label: "Archaludon", show: true },
  { value: "hydrapple", label: "Hydrapple", show: true },
  { value: "gouging-fire", label: "Gouging Fire", show: true },
  { value: "raging-bolt", label: "Raging Bolt", show: true },
  { value: "iron-boulder", label: "Iron Boulder", show: true },
  { value: "iron-crown", label: "Iron Crown", show: true },
  { value: "terapagos", label: "Terapagos", show: true },
  { value: "pecharunt", label: "Pecharunt", show: true },
  { value: "venusaur-mega", label: "Mega Venusaur", show: true },
  { value: "charizard-mega-x", label: "Mega Charizard X", show: true },
  { value: "charizard-mega-y", label: "Mega Charizard Y", show: true },
  { value: "blastoise-mega", label: "Mega Blastoise", show: true },
  { value: "beedrill-mega", label: "Mega Beedrill", show: true },
  { value: "pidgeot-mega", label: "Mega Pidgeot", show: true },
  { value: "raichu-mega-x", label: "Mega Raichu X", show: false },
  { value: "raichu-mega-y", label: "Mega Raichu Y", show: false },
  { value: "clefable-mega", label: "Mega Clefable", show: true },
  { value: "alakazam-mega", label: "Mega Alakazam", show: true },
  { value: "victreebel-mega", label: "Mega Victreebel", show: true },
  { value: "slowbro-mega", label: "Mega Slowbro", show: true },
  { value: "gengar-mega", label: "Mega Gengar", show: true },
  { value: "kangaskhan-mega", label: "Mega Kangaskhan", show: true },
  { value: "starmie-mega", label: "Mega Starmie", show: true },
  { value: "pinsir-mega", label: "Mega Pinsir", show: true },
  { value: "gyarados-mega", label: "Mega Gyarados", show: true },
  { value: "aerodactyl-mega", label: "Mega Aerodactyl", show: true },
  { value: "dragonite-mega", label: "Mega Dragonite", show: true },
  { value: "mewtwo-mega-x", label: "Mega Mewtwo X", show: true },
  { value: "mewtwo-mega-y", label: "Mega Mewtwo Y", show: true },
  { value: "meganium-mega", label: "Mega Meganium", show: true },
  { value: "feraligatr-mega", label: "Mega Feraligatr", show: true },
  { value: "ampharos-mega", label: "Mega Ampharos", show: true },
  { value: "steelix-mega", label: "Mega Steelix", show: true },
  { value: "scizor-mega", label: "Mega Scizor", show: true },
  { value: "heracross-mega", label: "Mega Heracross", show: true },
  { value: "skarmory-mega", label: "Mega Skarmory", show: true },
  { value: "houndoom-mega", label: "Mega Houndoom", show: true },
  { value: "tyranitar-mega", label: "Mega Tyranitar", show: true },
  { value: "sceptile-mega", label: "Mega Sceptile", show: true },
  { value: "blaziken-mega", label: "Mega Blaziken", show: true },
  { value: "swampert-mega", label: "Mega Swampert", show: true },
  { value: "gardevoir-mega", label: "Mega Gardevoir", show: true },
  { value: "sableye-mega", label: "Mega Sableye", show: true },
  { value: "mawile-mega", label: "Mega Mawile", show: true },
  { value: "aggron-mega", label: "Mega Aggron", show: true },
  { value: "medicham-mega", label: "Mega Medicham", show: true },
  { value: "manectric-mega", label: "Mega Manectric", show: true },
  { value: "sharpedo-mega", label: "Mega Sharpedo", show: true },
  { value: "camerupt-mega", label: "Mega Camerupt", show: true },
  { value: "altaria-mega", label: "Mega Altaria", show: true },
  { value: "banette-mega", label: "Mega Banette", show: true },
  { value: "chimecho-mega", label: "Mega Chimecho", show: false },
  { value: "absol-mega", label: "Mega Absol", show: true },
  { value: "absol-mega-z", label: "Mega Absol Z", show: false },
  { value: "glalie-mega", label: "Mega Glalie", show: true },
  { value: "salamence-mega", label: "Mega Salamence", show: true },
  { value: "metagross-mega", label: "Mega Metagross", show: true },
  { value: "latias-mega", label: "Mega Latias", show: true },
  { value: "latios-mega", label: "Mega Latios", show: true },
  { value: "rayquaza-mega", label: "Mega Rayquaza", show: true },
  { value: "staraptor-mega", label: "Mega Staraptor", show: false },
  { value: "lopunny-mega", label: "Mega Lopunny", show: true },
  { value: "garchomp-mega", label: "Mega Garchomp", show: true },
  { value: "garchomp-mega-z", label: "Mega Garchomp Z", show: false },
  { value: "lucario-mega", label: "Mega Lucario", show: true },
  { value: "lucario-mega-z", label: "Mega Lucario Z", show: false },
  { value: "abomasnow-mega", label: "Mega Abomasnow", show: true },
  { value: "gallade-mega", label: "Mega Gallade", show: true },
  { value: "froslass-mega", label: "Mega Froslass", show: true },
  { value: "heatran-mega", label: "Mega Heatran", show: false },
  { value: "darkrai-mega", label: "Mega Darkrai", show: false },
  { value: "emboar-mega", label: "Mega Emboar", show: true },
  { value: "excadrill-mega", label: "Mega Excadrill", show: true },
  { value: "audino-mega", label: "Mega Audino", show: true },
  { value: "scolipede-mega", label: "Mega Scolipede", show: true },
  { value: "scrafty-mega", label: "Mega Scrafty", show: true },
  { value: "eelektross-mega", label: "Mega Eelektross", show: true },
  { value: "chandelure-mega", label: "Mega Chandelure", show: true },
  { value: "golurk-mega", label: "Mega Golurk", show: false },
  { value: "chesnaught-mega", label: "Mega Chesnaught", show: true },
  { value: "delphox-mega", label: "Mega Delphox", show: true },
  { value: "greninja-mega", label: "Mega Greninja", show: true },
  { value: "pyroar-mega", label: "Mega Pyroar", show: true },
  { value: "floette-mega", label: "Mega Floette", show: true },
  { value: "meowstic-mega", label: "Mega Meowstic", show: false },
  { value: "malamar-mega", label: "Mega Malamar", show: true },
  { value: "barbaracle-mega", label: "Mega Barbaracle", show: true },
  { value: "dragalge-mega", label: "Mega Dragalge", show: true },
  { value: "hawlucha-mega", label: "Mega Hawlucha", show: true },
  { value: "zygarde-mega", label: "Mega Zygarde", show: true },
  { value: "diancie-mega", label: "Mega Diancie", show: true },
  { value: "crabominable-mega", label: "Mega Crabominable", show: false },
  { value: "golisopod-mega", label: "Mega Golisopod", show: false },
  { value: "drampa-mega", label: "Mega Drampa", show: true },
  { value: "magearna-mega", label: "Mega Magearna", show: false },
  { value: "zeraora-mega", label: "Mega Zeraora", show: false },
  { value: "falinks-mega", label: "Mega Falinks", show: true },
  { value: "scovillain-mega", label: "Mega Scovillain", show: false },
  { value: "glimmora-mega", label: "Mega Glimmora", show: false },
  { value: "tatsugiri-mega", label: "Mega Tatsugiri", show: false },
  { value: "baxcalibur-mega", label: "Mega Baxcalibur", show: false }
];

export const POKEMON_VISIBLE_OPTIONS = POKEMON_SEARCH_ENTRIES.filter(
  (entry) => entry.show
).map((entry) => ({ value: entry.value, label: entry.label }));

export const POKEMON_SEARCH_SET = new Set(
  POKEMON_SEARCH_ENTRIES.flatMap((entry) => [
    entry.value.toLowerCase(),
    entry.label.toLowerCase()
  ])
);
